# Generated by Django 4.0.1 on 2022-01-28 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=40, verbose_name='Prezime')),
                ('oib', models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Duljina polja je točno 11 znamenki!!!', regex='^\\d{11}$')], verbose_name='OIB')),
                ('item', models.CharField(default='', max_length=200, verbose_name='Oprema')),
                ('date_birth', models.DateField(verbose_name='Datum rođenja:')),
                ('date_work', models.DateField(verbose_name='Datum početka rada:')),
                ('gender', models.CharField(default='', max_length=1, validators=[django.core.validators.RegexValidator(code='nomatch', message='Samo M ili Ž su dozvoljene opcije.', regex='^[mMžŽ]{1}$')], verbose_name='Spol:')),
                ('address', models.CharField(default='', max_length=40, verbose_name='Prebivalište')),
                ('zip', models.CharField(default='', max_length=5, verbose_name='Poštanski broj')),
                ('city', models.CharField(default='', max_length=40, verbose_name='Grad')),
                ('nationality', models.CharField(default='', max_length=20, verbose_name='Državljanstvo')),
                ('edu_degree', models.CharField(default='', max_length=15, verbose_name='Stručna sprema')),
                ('last_school', models.CharField(default='', max_length=100, verbose_name='Zadnja završena škola')),
                ('iban', models.CharField(default='', max_length=21, validators=[django.core.validators.RegexValidator(code='nomatch', message='Duljina polja je točno 21 (2 velika slova + 19 znamenki)!!!', regex='^[A-Za-z]{2}\\d{19}$')], verbose_name='IBAN')),
                ('bank', models.CharField(default='', editable=False, max_length=60, null=True, verbose_name='Banka')),
                ('swift', models.CharField(default='', editable=False, max_length=20, null=True, verbose_name='Swift br.')),
                ('exp_years', models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Samo znamenke. Najmanje jedna znamenka', regex='^\\d{2}|\\d{1}$')], verbose_name='Staž - godine')),
                ('exp_months', models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='amo znamenke. Najmanje jedna znamenka', regex='^\\d{2}|\\d{1}$')], verbose_name='Staž - mjesec')),
                ('exp_days', models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Samo znamenke. Najmanje jedna znamenka', regex='^\\d{3}|\\d{2}|\\d{1}$')], verbose_name='Staž - dani')),
            ],
        ),
    ]
