# Generated by Django 4.0.1 on 2022-01-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('oib', models.CharField(max_length=11)),
                ('date_birth', models.DateTimeField(verbose_name='Datum rođenja:')),
            ],
        ),
    ]
