# Generated by Django 4.0.1 on 2022-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=40, verbose_name='Prebivalište'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='', max_length=40, verbose_name='Grad'),
        ),
        migrations.AddField(
            model_name='employee',
            name='edu_degree',
            field=models.CharField(default='', max_length=15, verbose_name='Stručna sprema'),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(default='', max_length=15, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='item',
            field=models.CharField(default='', max_length=200, verbose_name='Oprema'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_school',
            field=models.CharField(default='', max_length=100, verbose_name='Zadnja završena škola'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='', max_length=20, verbose_name='Državljanstvo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zip',
            field=models.CharField(default='', max_length=5, verbose_name='Poštanski broj'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Prezime'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='oib',
            field=models.CharField(max_length=11, verbose_name='OIB'),
        ),
    ]
