# Generated by Django 4.0.1 on 2022-01-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_address_employee_city_employee_edu_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(verbose_name='Datum rođenja:'),
        ),
    ]
