# Generated by Django 4.0.1 on 2022-01-31 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_exp_days_alter_employee_exp_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exp_days',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Samo znamenke. Najmanje jedna znamenka. Max 365 dana', regex='^([0123]{1}\\d{2}|\\d{2}|\\d{1}){1}$')], verbose_name='Staž - dani'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exp_months',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Samo znamenke. Najmanje jedna znamenka. Max 11 mjeseci', regex='^([01]{1}\\d{1}|\\d{1}){1}$')], verbose_name='Staž - mjeseci'),
        ),
    ]
