# Generated by Django 4.0.1 on 2022-01-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='iban',
            field=models.CharField(default='', max_length=22, verbose_name='IBAN'),
        ),
    ]
