# Generated by Django 4.0.1 on 2022-01-25 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='oib2',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Duljina polja je točno 11 znamenki!!!', regex='^\\d{11}$')]),
        ),
    ]
