# Generated by Django 4.0.1 on 2022-01-31 10:50

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_exp_days_alter_employee_exp_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Prezime'),
        ),
    ]
