# Generated by Django 4.0.1 on 2022-01-25 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_oib2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='oib2',
        ),
        migrations.AlterField(
            model_name='employee',
            name='iban',
            field=models.CharField(default='', max_length=21, validators=[django.core.validators.RegexValidator(code='nomatch', message='Duljina polja je točno 21 (2 velika slova + 19 znamenki)!!!', regex='^\\d{11}$')], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='oib',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Duljina polja je točno 11 znamenki!!!', regex='^\\d{11}$')]),
        ),
    ]
