# Generated by Django 4.0.1 on 2022-01-31 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_bank_country_alter_employee_exp_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exp_months',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Samo znamenke. Najmanje jedna znamenka.', regex='^([01]{1}\\d{1}|\\d{1}){1}$')], verbose_name='Staž - mjeseci'),
        ),
    ]
