# Generated by Django 4.0.1 on 2022-01-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_name_employee_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='', max_length=60, verbose_name='Banka'),
        ),
    ]
