# Generated by Django 4.0.1 on 2022-01-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_oib'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exp_in_company_days',
            field=models.CharField(default='', editable=False, max_length=120, null=True, verbose_name='Staž u firmi - dani'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_in_company_months',
            field=models.CharField(default='', editable=False, max_length=120, null=True, verbose_name='Staž u firmi - mjeseci'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_in_company_years',
            field=models.CharField(default='', editable=False, max_length=3, null=True, verbose_name='Staž u firmi - godine'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_total_days',
            field=models.CharField(default='', editable=False, max_length=120, null=True, verbose_name='staž ukupno - dani'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_total_months',
            field=models.CharField(default='', editable=False, max_length=120, null=True, verbose_name='Staž ukupno - mjeseci'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_total_years',
            field=models.CharField(default='', editable=False, max_length=120, null=True, verbose_name='Staž ukupno - godine'),
        ),
    ]
