# Generated by Django 4.0.1 on 2022-01-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='Banka'),
        ),
    ]
